### PR TITLE
UI/notification

### PR DESCRIPTION
**Pull request by Sheriff-Oladimeji**
## Related Issue(s)

Fixes # Resolves # Closes #

## Proposed Changes

[//]: # '[List down the specific changes you have made in this pull request.]'

- [x]

## Checklist

- [x] I have followed the repository's contribution guidelines.
- [x] I have added necessary documentation or updated existing documentation.
- [x] My code follows the established code style and formatting of the project.
- [x] I have tested my changes and they function as expected.
- [ ] I have added suitable unit tests (if applicable).

## To-Do

- [ ]

### CODE REVIEW

**Review by techyNonso — CHANGES_REQUESTED** [review]
Why do you have a notifications folder outside of dashboard folder

**Comment by Sheriff-Oladimeji** [comment]
> Why do you have a notifications folder outside of dashboard folder

It's inside, please check again

**Comment by Sheriff-Oladimeji** [comment]
> Why do you have a notifications folder outside of dashboard folder

It's inside; please check again

**Comment by techyNonso** [comment]
I already deleted it before asking you to make a pull , so you won't see it

**Pull request closed without merging**
