### PR TITLE
migrate: particle.network

### LINKED ISSUE #99: auth flow: migrate from web3auth -> particle.network
- [ ] migrate auth flow to particle.network
- [ ] update env vars in vercel
- [ ] update env vars in ci @Nasfame

### PR DESCRIPTION
**Pull request by techyNonso**
### Description

- [x] Resolves #99 

### Checklist

- [x] I have followed the repository's contribution guidelines.
- [x] I have added necessary documentation or updated existing documentation.
- [x] My code follows the established code style and formatting of the project.
- [x] I have tested my changes and they function as expected.
- [x] I have added suitable unit tests (if applicable).
#99 

To be reviewed by: @Nasfame

### CODE REVIEW

**Comment by techyNonso** [comment]
for particle.ts, my accept the code in my branch

Please also fix lock file issues

**Comment by Nasfame** [comment]
@techyNonso please update the branch and do pnpm install.

**Comment by Nasfame** [comment]
@techyNonso can u update ur branch, lets merge ur branch on the next standup call

**Comment by Nasfame** [comment]
can u update @techyNonso ? resolve the conflicts !

**Comment by Nasfame** [comment]
@techyNonso fix the build

**Review by Nasfame — APPROVED** [review]
LGTM; tested preview (little buggy) it would have been great we could preserve web3auth but that's already put up tags.

**Pull request merged**
