### PR TITLE
revamp/ui: dashboard[not empty]

### PR DESCRIPTION
**Pull request by Codebox124**
### Description

- [x] Resolves 

### Checklist
Decenter-AI (5)

- [x] I have followed the repository's contribution guidelines.
- [x] I have added necessary documentation or updated existing documentation.
- [x] My code follows the established code style and formatting of the project.
- [x] I have tested my changes and they function as expected.
- [x] I have added suitable unit tests (if applicable).

To be reviewed by: @Nasfame

### CODE REVIEW

**Comment by Nasfame** [comment]
@Codebox124 kindly update the pr

**Comment by Nasfame** [comment]
@Codebox124 kindly update and resolve conflicts

**Comment by Nasfame** [comment]
@Codebox124 there are some conflicts, can u look into it please

**Comment by Codebox124** [comment]
solved conflict

**Review by techyNonso — CHANGES_REQUESTED** [review]
image
This does not fit to screen

**Review by techyNonso — APPROVED** [review]

**Pull request merged**
